name: memories_scrapbook
description: collaborative memories scrapbook for people living with dementia

on: [push, workflow_dispatch]

jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - run: flutter test #runs everything in test directory
publish_to: none

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  
  supabase_flutter: ^1.10.1
  image_picker: ^0.8.3
  postgrest: ^1.3.1
  tuple: ^2.0.1
  video_player: ^2.6.1
  file_picker: ^5.3.2
  path: ^1.8.3
  audioplayers: ^4.1.0
  better_player: ^0.0.83
  wakelock: ^0.6.2
  wakelock_windows: ^0.2.1

dependency_overrides:
  win32: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/