name: memories_scrapbook
description: collaborative memories scrapbook for people living with dementia

on: [push, workflow_dispatch]

jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - run: flutter test #runs everything in test directory
publish_to: none

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

  supabase_flutter: ^1.10.1
  image_picker: ^0.8.3
  postgrest: ^1.3.1
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/